import React, { useState } from 'react';

// First-launch disclaimer. Blocks the UI until the user checks the
// "I understand" box and clicks Continue. The checkbox flips
// prefs.disclaimerAcknowledged so this won't show on subsequent launches.
//
// Kept deliberately text-heavy. Every bullet here maps directly to a point
// in COMPLIANCE.md — if you edit one, edit the other.
export default function DisclaimerModal({ onAcknowledge }) {
  const [checked, setChecked] = useState(false);
  const [saving, setSaving] = useState(false);
  const [err, setErr] = useState(null);

  const onContinue = async () => {
    if (!checked || saving) return;
    setSaving(true);
    setErr(null);
    try {
      await window.cowork?.prefs?.save?.({ disclaimerAcknowledged: true });
      onAcknowledge?.();
    } catch (x) {
      setErr(String(x?.message || x));
      setSaving(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-ink-950/80 backdrop-blur-sm">
      <div className="w-[640px] max-w-[calc(100vw-2rem)] max-h-[calc(100vh-2rem)] overflow-y-auto bg-ink-900 border border-ink-700 rounded-lg shadow-2xl">
        <div className="px-5 py-4 border-b border-ink-700 flex items-center gap-3">
          <div className="flex-1 min-w-0">
            <div className="text-ink-50 text-sm font-semibold">Before you continue</div>
            <div className="text-ink-400 text-[11.5px] mt-0.5">
              Claude Desktop replica · unofficial community build
            </div>
          </div>
          <span className="text-[9.5px] font-semibold uppercase tracking-wider px-1.5 py-0.5 rounded bg-accent-500/20 text-accent-500 border border-accent-500/40">
            Alpha
          </span>
        </div>

        <div className="px-5 py-4 space-y-3 text-[12.5px] text-ink-200 leading-relaxed">
          <p className="text-ink-300">
            This is an independent, community-built front-end that drives the
            official <code className="font-mono text-[11.5px]">claude</code> CLI.
            Please read the notes below before using it.
          </p>

          <Note title="Not affiliated with Anthropic">
            The developer of this app is not affiliated with, employed by, or
            endorsed by Anthropic. No permission was requested or granted by
            Anthropic or the Claude team to build this replica. &ldquo;Claude&rdquo;
            and &ldquo;Anthropic&rdquo; are trademarks of Anthropic — this project
            is a third-party UI that happens to talk to their CLI.
          </Note>

          <Note title="This app runs offline">
            The app itself does not send your prompts, files, or account data
            anywhere. All network traffic you see is generated by the tools Claude
            invokes (WebSearch, WebFetch, etc.) and by the official CLI talking
            to Anthropic&rsquo;s API under your own account.
          </Note>

          <Note title="Login is handled by the official CLI">
            Sign-in, token refresh, and account status are all done by the
            official <code className="font-mono text-[11.5px]">claude</code>{' '}
            binary. This app never sees or stores your credentials. If you&rsquo;re
            signed out, it opens a real terminal so you can sign in directly.
          </Note>

          <Note title="You need Electron prerequisites">
            Running this app requires a working Node/Electron environment and
            the Claude CLI installed on your machine. If you hit a build or
            runtime issue, that&rsquo;s on you to debug — the developer cannot
            provide support for environment setup.
          </Note>

          <Note title="Alpha / beta software">
            Expect bugs, breaking changes, and rough edges. Don&rsquo;t use this
            for anything you can&rsquo;t afford to lose. Always review what the
            agent is about to do before approving — especially in{' '}
            <span className="text-accent-500">Jailbroken</span> shell mode.
          </Note>
        </div>

        <div className="px-5 py-3 border-t border-ink-700 bg-ink-900/60">
          <label className="flex items-start gap-2 cursor-pointer select-none">
            <input
              type="checkbox"
              checked={checked}
              onChange={(e) => setChecked(e.target.checked)}
              className="mt-0.5 accent-accent-500"
            />
            <span className="text-[12px] text-ink-200">
              I&rsquo;ve read the notes above and understand this is an
              unofficial alpha build, not affiliated with Anthropic.
            </span>
          </label>
          {err && (
            <div className="mt-2 text-[11px] text-accent-500">{err}</div>
          )}
          <div className="mt-3 flex justify-end">
            <button
              type="button"
              disabled={!checked || saving}
              onClick={onContinue}
              className={`text-xs font-medium px-3.5 py-1.5 rounded-md transition-colors
                ${checked && !saving
                  ? 'bg-accent-500 text-ink-950 hover:bg-accent-400'
                  : 'bg-ink-800 text-ink-500 cursor-not-allowed'}`}
            >
              {saving ? 'Saving…' : 'Continue'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

function Note({ title, children }) {
  return (
    <div className="px-3 py-2 rounded-md bg-ink-800/50 border border-ink-700/60">
      <div className="text-ink-100 text-[12px] font-medium mb-0.5">{title}</div>
      <div className="text-ink-300 text-[11.5px]">{children}</div>
    </div>
  );
}
